_target_: online_mirror_descent.make_learner
_partial_: true
buffer_size: 100_000
buffer_batch_size: 256
num_updates: 4000
lr: 0.001
epsilon_start: 1.0
epsilon_finish: 0.1
epsilon_anneal_time: 1_000_000
temperature: 20.0
alpha: 0.99
discount_factor: 0.99
use_mirror_update: true
use_dqn: false
target_update_interval: 200
training_starts: 1000
training_interval: 10
num_envs: ${training.num_envs}